teams = [
{'id': 'BUF', 'city': 'Buffalo', 'lname': 'Bills', 'conf': 'AFC', 'div': 'East', 'url': 'guessingfootball.com', 'twtr': 'buffalobills'},
{'id': 'MIA', 'city': 'Miami', 'lname': 'Dolphins', 'conf': 'AFC', 'div': 'East', 'url': 'guessingfootball.com', 'twtr': 'MiamiDolphins'},
{'id': 'NE', 'city': 'New England', 'lname': 'Patriots', 'conf': 'AFC', 'div': 'East', 'url': 'guessingfootball.com', 'twtr': 'Patriots'},
{'id': 'NYJ', 'city': 'New York', 'lname': 'Jets', 'conf': 'AFC', 'div': 'East', 'url': 'guessingfootball.com', 'twtr': 'nyjets'},
{'id': 'BAL', 'city': 'Baltimore', 'lname': 'Ravens', 'conf': 'AFC', 'div': 'North', 'url': 'guessingfootball.com', 'twtr': 'Ravens'},
{'id': 'CIN', 'city': 'Cincinnati', 'lname': 'Bengals', 'conf': 'AFC', 'div': 'North', 'url': 'guessingfootball.com', 'twtr': 'Bengals'},
{'id': 'CLE', 'city': 'Cleveland', 'lname': 'Browns', 'conf': 'AFC', 'div': 'North', 'url': 'guessingfootball.com', 'twtr': 'Browns'},
{'id': 'PIT', 'city': 'Pittsburgh', 'lname': 'Steelers', 'conf': 'AFC', 'div': 'North', 'url': 'guessingfootball.com', 'twtr': 'steelers'},
{'id': 'HOU', 'city': 'Houston', 'lname': 'Texans', 'conf': 'AFC', 'div': 'South', 'url': 'guessingfootball.com', 'twtr': 'HoustonTexans'},
{'id': 'IND', 'city': 'Indianapolis', 'lname': 'Colts', 'conf': 'AFC', 'div': 'South', 'url': 'guessingfootball.com', 'twtr': 'Colts'},
{'id': 'JAC', 'city': 'Jacksonville', 'lname': 'Jaguars', 'conf': 'AFC', 'div': 'South', 'url': 'guessingfootball.com', 'twtr': 'jaguars'},
{'id': 'TEN', 'city': 'Tennessee', 'lname': 'Titans', 'conf': 'AFC', 'div': 'South', 'url': 'guessingfootball.com', 'twtr': 'TennesseeTitans'},
{'id': 'DEN', 'city': 'Denver', 'lname': 'Broncos', 'conf': 'AFC', 'div': 'West', 'url': 'guessingfootball.com', 'twtr': 'Broncos'},
{'id': 'KC', 'city': 'Kansas City', 'lname': 'Chiefs', 'conf': 'AFC', 'div': 'West', 'url': 'guessingfootball.com', 'twtr': 'KCChiefs'},
{'id': 'LV', 'city': 'Las Vegas', 'lname': 'Raiders', 'conf': 'AFC', 'div': 'West', 'url': 'guessingfootball.com', 'twtr': 'RAIDERS'},
{'id': 'LAC', 'city': 'Los Angeles', 'lname': 'Chargers', 'conf': 'AFC', 'div': 'West', 'url': 'guessingfootball.com', 'twtr': 'chargers'},
{'id': 'DAL', 'city': 'Dallas', 'lname': 'Cowboys', 'conf': 'NFC', 'div': 'East', 'url': 'guessingfootball.com', 'twtr': 'dallascowboys'},
{'id': 'NYG', 'city': 'New York', 'lname': 'Giants', 'conf': 'NFC', 'div': 'East', 'url': 'guessingfootball.com', 'twtr': 'Giants'},
{'id': 'PHI', 'city': 'Philadelphia', 'lname': 'Eagles', 'conf': 'NFC', 'div': 'East', 'url': 'guessingfootball.com', 'twtr': 'Eagles'},
{'id': 'WAS', 'city': 'Washington', 'lname': 'Redskins', 'conf': 'NFC', 'div': 'East', 'url': 'guessingfootball.com', 'twtr': 'Redskins'},
{'id': 'CHI', 'city': 'Chicago', 'lname': 'Bears', 'conf': 'NFC', 'div': 'North', 'url': 'guessingfootball.com', 'twtr': 'ChicagoBears'},
{'id': 'DET', 'city': 'Detroit', 'lname': 'Lions', 'conf': 'NFC', 'div': 'North', 'url': 'guessingfootball.com', 'twtr': 'Lions'},
{'id': 'GB', 'city': 'Green Bay', 'lname': 'Packers', 'conf': 'NFC', 'div': 'North', 'url': 'guessingfootball.com', 'twtr': 'packers'},
{'id': 'MIN', 'city': 'Minnesota', 'lname': 'Vikings', 'conf': 'NFC', 'div': 'North', 'url': 'guessingfootball.com', 'twtr': 'Vikings'},
{'id': 'ATL', 'city': 'Atlanta', 'lname': 'Falcons', 'conf': 'NFC', 'div': 'South', 'url': 'guessingfootball.com', 'twtr': 'Atlanta_Falcons'},
{'id': 'CAR', 'city': 'Carolina', 'lname': 'Panthers', 'conf': 'NFC', 'div': 'South', 'url': 'guessingfootball.com', 'twtr': 'Panthers'},
{'id': 'NO', 'city': 'New Orleans', 'lname': 'Saints', 'conf': 'NFC', 'div': 'South', 'url': 'guessingfootball.com', 'twtr': 'Saints'},
{'id': 'TB', 'city': 'Tampa Bay', 'lname': 'Buccaneers', 'conf': 'NFC', 'div': 'South', 'url': 'guessingfootball.com', 'twtr': 'TBBuccaneers'},
{'id': 'ARI', 'city': 'Arizona', 'lname': 'Cardinals', 'conf': 'NFC', 'div': 'West', 'url': 'guessingfootball.com', 'twtr': 'AZCardinals'},
{'id': 'SF', 'city': 'San Francisco', 'lname': '49ers', 'conf': 'NFC', 'div': 'West', 'url': 'guessingfootball.com', 'twtr': '49ers'},
{'id': 'SEA', 'city': 'Seattle', 'lname': 'Seahawks', 'conf': 'NFC', 'div': 'West', 'url': 'guessingfootball.com', 'twtr': 'Seahawks'},
{'id': 'LA', 'city': 'Los Angeles', 'lname': 'Rams', 'conf': 'NFC', 'div': 'West', 'url': 'guessingfootball.com', 'twtr': 'RamsNFL'}
] 