# Generated by Django 5.2.1 on 2025-08-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_quarter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game',
            name='time_remaining',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
