# Generated by Django 5.2.1 on 2025-08-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_game_current_quarter_game_game_status_game_is_live_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='losses_2024',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='rank_2024_conference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='rank_2024_division',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='rank_2024_league',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='ties_2024',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='wins_2024',
            field=models.IntegerField(default=0),
        ),
    ]
