# Generated by Django 5.2.1 on 2025-08-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_team_losses_2024_team_rank_2024_conference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='points_against_2024',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='points_for_2024',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='rank_2024_defense_conference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='rank_2024_defense_division',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='rank_2024_defense_league',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='rank_2024_offense_conference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='rank_2024_offense_division',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='rank_2024_offense_league',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
